In [1]:
import pandas as pd
import numpy as np

# Create dataset
np.random.seed(42)

data = {
    "Student_ID": range(1, 101),
    "Marks": np.random.randint(40, 100, 100),
    "Department": np.random.choice(["CS", "IT", "EC"], 100)
}

df = pd.DataFrame(data)
df.head()

   Student_ID  Marks Department
0           1     78         IT
1           2     91         EC
2           3     68         CS
3           4     54         IT
4           5     82         CS

In [ ]:
# Simple random sampling (select 10 students) -> work on indexing value
simple_random_sample = df.sample(n=10, random_state=1)
simple_random_sample

# sample(n=10) → randomly selects 10 rows
# No bias
# Best for small, uniform population

    Student_ID  Marks Department
80          81     79         EC
84          85     93         IT
33          34     83         CS
81          82     43         EC
93          94     49         EC
17          18     63         CS
36          37     66         IT
82          83     41         EC
69          70     86         CS
65          66     92         CS

In [ ]:
# Systematic sampling ->work on indexing value
k = 13  # every 10th student
systematic_sample = df.iloc[::k]
systematic_sample
len(systematic_sample)
# print(systematic_sample)

# iloc[::10] → jump of 10
# Very fast
# Used in ordered data

8

In [ ]:
# Stratified sampling (equal samples from each department) we are targating column , work on catagorical value
stratified_sample = df.groupby("Department", group_keys=False).apply(
    lambda x: x.sample(5, random_state=1)
)

stratified_sample

# Population divided into homogeneous groups (strata)
# groupby("Department") → create strata
# sample(5) → sample from each group
# Ensures representation

/var/folders/m_/mkmgvrh50sjbfhzz0vscx1tw0000gn/T/ipykernel_19251/3815522164.py:2: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  stratified_sample = df.groupby("Department", group_keys=False).apply(

    Student_ID  Marks Department
5            6     47         CS
75          76     74         CS
8            9     97         CS
52          53     46         CS
65          66     92         CS
14          15     92         EC
74          75     86         EC
18          19     42         EC
56          57     57         EC
66          67     41         EC
64          65     65         IT
87          88     93         IT
9           10     58         IT
71          72     46         IT
91          92     83         IT

In [9]:
# Stratified random sampling (proportional)
stratified_random_sample = df.groupby("Department", group_keys=False).apply(
    lambda x: x.sample(frac=0.1, random_state=42)
)

stratified_random_sample

/var/folders/m_/mkmgvrh50sjbfhzz0vscx1tw0000gn/T/ipykernel_19251/2383441807.py:2: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  stratified_random_sample = df.groupby("Department", group_keys=False).apply(

    Student_ID  Marks Department
35          36     88         CS
24          25     69         CS
10          11     62         CS
75          76     74         CS
80          81     79         EC
93          94     49         EC
21          22     41         EC
39          40     67         EC
43          44     86         IT
84          85     93         IT

In [13]:
# Select one cluster randomly
selected_cluster = np.random.choice(df["Department"].unique())
cluster_sample = df[df["Department"] == selected_cluster]

selected_cluster, cluster_sample


# Divide population into clusters
# Select entire cluster(s)
# One department selected
# All students from that department included
# Cost-effective, but less accurate

('EC',
     Student_ID  Marks Department
 1            2     91         EC
 7            8     78         EC
 14          15     92         EC
 18          19     42         EC
 21          22     41         EC
 22          23     63         EC
 23          24     83         EC
 25          26     77         EC
 26          27     41         EC
 28          29     60         EC
 31          32     97         EC
 34          35     64         EC
 38          39     81         EC
 39          40     67         EC
 42          43     54         EC
 44          45     90         EC
 45          46     83         EC
 47          48     91         EC
 49          50     42         EC
 51          52     90         EC
 55          56     78         EC
 56          57     57         EC
 58          59     64         EC
 59          60     99         EC
 61          62     89         EC
 62          63     97         EC
 66          67     41         EC
 67          68     59         EC
 68          69     67         EC
 73          74     47         EC
 74          75     86         EC
 76          77     53         EC
 77          78     56         EC
 80          81     79         EC
 81          82     43         EC
 82          83     41         EC
 93          94     49         EC
 95          96     53         EC
 97          98     87         EC)

In [14]:
# All available clusters
clusters = df["Department"].unique()
clusters

array(['IT', 'EC', 'CS'], dtype=object)

In [20]:
# Select 2 clusters randomly
selected_clusters = np.random.choice(clusters, size=3, replace=False)
selected_clusters

array(['EC', 'CS', 'IT'], dtype=object)

In [21]:
# Multiple cluster sampling
multi_cluster_sample = df[df["Department"].isin(selected_clusters)]
multi_cluster_sample

    Student_ID  Marks Department
0            1     78         IT
1            2     91         EC
2            3     68         CS
3            4     54         IT
4            5     82         CS
..         ...    ...        ...
95          96     53         EC
96          97     70         CS
97          98     87         EC
98          99     54         IT
99         100     47         CS

[100 rows x 3 columns]